branches:
  only:
    - /^Development-.*$/
    - /^Minecraft-.*$/
language: java
sudo: false
jdk:
- oraclejdk8
before_install:
- chmod +x gradlew
install: ./gradlew setupCIWorkspace -S --debug
script: ./gradlew build -S --debug
after_success:
  - ./gradlew uploadJars -S --debug
  - ./gradlew makeChangelog curseforge -S --debug
  - ./gradlew createGithubBranches -S --debug

