branches:
  only:
    - /^Development-.*$/
    - /^Minecraft-.*$/
language: java
sudo: false
jdk:
- oraclejdk8
before_install:
- chmod +x gradlew
install: ./gradlew setupCIWorkspace -S -i
script: ./gradlew build -S -i
after_success:
  - ./gradlew uploadJars -S -i
  - ./gradlew makeChangelog curseforge -S -i
  - ./gradlew createGithubBranches -S -i

